model_name: gpt-4o

dot_global_config_health_check: true

########################################################
# Debugging
########################################################
agent:
  chat_agent_model: gemini/gemini-2.0-flash


llm_config:
  retry:
    max_attempts: 3
    min_wait_seconds: 1
    max_wait_seconds: 5


weird_quirk:
  temperature: 0.5
  max_tokens: 100000

########################################################
# Debugging
########################################################
logging:
  verbose: true
  format:
    show_time: false
    show_session_id: true
    location:
      enabled: true
      show_file: true
      show_function: true
      show_line: true
      # Configure which log levels show location information
      show_for_info: false
      show_for_debug: true
      show_for_warning: true
      show_for_error: true
  levels:
    debug: false  # Suppress all debug logs
    info: true    # Show info logs
    warning: true # Show warning logs
    error: true   # Show error logs
    critical: true # Show critical logs
